name: C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Build
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: program
        path: program