name: C++ CI

on:
    push:
      branches: [ '*' ]
    pull_request:
      branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make automake autoconf
        sudo apt-get install -y devscripts debhelper build-essential

    - name: Generate build system
      run: |
        autoreconf --install
        ./configure

    - name: Build
      run: make

    - name: Create distribution
      run: make dist

    - name: Build Debian package
      run: make deb

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: program
        path: program

    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: program-dist
        path: program-*.tar.gz

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: program-deb
        path: debian-build/*.deb